#!/bin/sh

key=$1
value=$2

for dir in $(ls -d ./*); do 
  if [ -d "$dir" ]; then
    echo ""
    echo "============================"
    echo "Checking status for: $dir"
    cd $dir
    git st
    cd ../
    echo ""
    echo "----------------------------"
    echo "";
  fi;
done;
