#!/bin/sh

key=$1
value=$2

for dir in $(find . -d 1); do 
  if [ -d "$dir" ]; then 
    echo ""
    echo "============================"
    echo "Pulling code for $dir"
    cd $dir
    git pull
    cd ../
    echo ""
    echo "----------------------------"
    echo ""; 
  fi; 
done;
